import Metrics from "../../Themes/Metrics";

export const FONT_SIZE = {
    very_tiny: Metrics.rfv(6),
    tiny: Metrics.rfv(8),
    small_tiny: Metrics.rfv(10),
    small: Metrics.rfv(12),
    small_medium: Metrics.rfv(14),
    medium: Metrics.rfv(16),
    medium_extra: Metrics.rfv(18),
    regular: Metrics.rfv(20),
    regular_extra: Metrics.rfv(22),
    large: Metrics.rfv(24),
    extra_large: Metrics.rfv(48),
  };
  export const industries = [
    'Accounting',
    'Airlies/Aviation',
    'Alternateive Medicine',
    'Animation',
    'Apparel & Fashion',
    'Architecture & Planning',
    'Arts and Crafts',
    'Automative',
    'Aviation & Aerospace',
    'Banking',
    'Biotechnology',
    'Broadcast Media',
    'Building Materials',
    'Business Supplies and Equipments',
    'Capital Markets',
    'Chemicals',
    'Civic & Social Organization',
    'Civil Engieering',
    'Commercial Real Estate',
    'Computer & Network Secutiry',
    'Computer Games',
    'Computer Hardware',
    'Computer Networking',
    'Computer Software',
    'Internet',
    'Construction',
    'Consumer Electronics',
    'Consumer Goods',
    'Dairy',
    'Defence & Space',
    'Design',
    'Education Management',
    'E-Learning',
    'Entertainment',
    'Event Services',
    'Farming',
    'Financial Service',
    'Food Production',
    'Furniture',
    'Goverment Administartion',
    'Graphic Design',
    'Haelth Wellness & Fitness',
    'Higner Eduction',
    'Hospital & Health Care',
    'Hospitality',
    'Human Resource',
    'Import and Export',
    'Individual & Family Services',
    'Industrial Automation',
    'Information Services',
    'Information Technology and Services',
    'Insurance',
    'International Affairs',
    'International Trade and Developement',
    'Investment Banking',
    'Investment Management',
    'Judiciary',
    'Law Enforcement',
    'Law Pracitce',
    'Legal Services',
    'Legislative Office',
    'Leisure, Travel and Tourism',
    'Libraries',
    'Logistic and Supply Chain',
    'Luxury Goods & Services',
    'Machinery',
    'Management Consulting',
    'Maritime',
    'Market Research',
    'Marketing and Advertising',
    'Mechanical or Industrial Engineering',
    'Media Production',
    'Media Devices',
    'Media Practice',
    'Mental Health Care',
    'Military',
    'Mining & Metals',
    'Motion Pictures and Film',
    'Museums and Institution',
    'Music',
    'Nanotechnology',
    'Newspapers',
    'Nonprofit Organization Management',
    'Oil & Energy',
    'Online Media',
    'Outsourcing/Offshoring',
    'Package/Freight Delivery',
    'Packading and Containers',
    'Paper & Forest Product',
    'Performing Arts',
    'pharmaceticals',
    'Writing and Editing',
    'Electrical Trader',
    'Electrical Contractor',
    'End User',
  ];
  const ErrorText = props => {
    const {errorMsg} = props;
    return <Text style={{...styles.errorText, ...props.style}}>{errorMsg}</Text>;
  };